const {parseObject} = require('./utils');

const meminfoMap = new Map([
	['MemTotal', (obj, v) => obj.total = parseInt(v)],
	['MemFree', (obj, v) => obj.free = parseInt(v)],
	['MemAvailable', (obj, v) => obj.available = parseInt(v)],
	['Buffers', (obj, v) => obj.buffers = parseInt(v)],
	['Cached', (obj, v) => obj.cached = parseInt(v)],
	['SwapCached', (obj, v) => obj.swapCached = parseInt(v)],
	['Active', (obj, v) => obj.active = parseInt(v)],
	['Inactive', (obj, v) => obj.inactive = parseInt(v)],
	['SwapTotal', (obj, v) => obj.swapTotal = parseInt(v)],
	['SwapFree', (obj, v) => obj.swapFree = parseInt(v)],
	['Dirty', (obj, v) => obj.dirty = parseInt(v)],
	['Writeback', (obj, v) => obj.writeback = parseInt(v)],
	['AnonPages', (obj, v) => obj.anonPages = parseInt(v)],
	['Mapped', (obj, v) => obj.mapped = parseInt(v)],
	['Shmem', (obj, v) => obj.shmem = parseInt(v)],
	['KReclaimable', (obj, v) => obj.kernelReclaimable = parseInt(v)],
	['Slab', (obj, v) => obj.slab = parseInt(v)],
	['SReclaimable', (obj, v) => obj.slabReclaimable = parseInt(v)],
	['SUnreclaim', (obj, v) => obj.slabUnreclaimable = parseInt(v)],
	['KernelStack', (obj, v) => obj.kernelStack = parseInt(v)],
	['PageTables', (obj, v) => obj.pageTables = parseInt(v)],
	['Bounce', (obj, v) => obj.bounceBuffers = parseInt(v)],
	['WritebackTmp', (obj, v) => obj.writebackTmp = parseInt(v)],
	['CommitLimit', (obj, v) => obj.commitLimit = parseInt(v)],
	['VmallocTotal', (obj, v) => obj.vmallocTotal = parseInt(v)],
	['HardwareCorrupted', (obj, v) => obj.hardwareCorrupted = parseInt(v)],
	['AnonHugePages', (obj, v) => obj.anonHugePages = parseInt(v)],
	['ShmemHugePages', (obj, v) => obj.shmemHugePages = parseInt(v)],
	['ShmemPmdMapped', (obj, v) => obj.shmemPmdMapped = parseInt(v)],
	['HugePages_Total', (obj, v) => obj.hugepagesTotal = parseInt(v)],
	['HugePages_Free', (obj, v) => obj.hugepagesFree = parseInt(v)],
	['HugePages_Rsvd', (obj, v) => obj.hugepagesReserved = parseInt(v)],
	['HugePages_Surp', (obj, v) => obj.hugepagesSurplus = parseInt(v)],
	['Hugepagesize', (obj, v) => obj.hugepageSize = parseInt(v)],
	['DirectMap4k', (obj, v) => obj.directMap4K = parseInt(v)],
	['DirectMap2M', (obj, v) => obj.directMap2M = parseInt(v)],
	['DirectMap4M', (obj, v) => obj.directMap4M = parseInt(v)],
	['DirectMap1G', (obj, v) => obj.directMap1G = parseInt(v)],
]);

module.exports = src => parseObject(src, meminfoMap, {directMap4K: 0, directMap2M: 0, directMap4M: 0, directMap1G: 0});
